package com.zero.entity;

import java.io.Serializable;

public class UserOpertion implements Serializable {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_opertion.uuid
     *
     * @mbg.generated
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_opertion.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_opertion.user_ip
     *
     * @mbg.generated
     */
    private String userIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_opertion.opt_name
     *
     * @mbg.generated
     */
    private String optName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_opertion.opt_time
     *
     * @mbg.generated
     */
    private String optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_opertion.uuid
     *
     * @return the value of user_opertion.uuid
     *
     * @mbg.generated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_opertion.uuid
     *
     * @param uuid the value for user_opertion.uuid
     *
     * @mbg.generated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_opertion.name
     *
     * @return the value of user_opertion.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_opertion.name
     *
     * @param name the value for user_opertion.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_opertion.user_ip
     *
     * @return the value of user_opertion.user_ip
     *
     * @mbg.generated
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_opertion.user_ip
     *
     * @param userIp the value for user_opertion.user_ip
     *
     * @mbg.generated
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_opertion.opt_name
     *
     * @return the value of user_opertion.opt_name
     *
     * @mbg.generated
     */
    public String getOptName() {
        return optName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_opertion.opt_name
     *
     * @param optName the value for user_opertion.opt_name
     *
     * @mbg.generated
     */
    public void setOptName(String optName) {
        this.optName = optName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_opertion.opt_time
     *
     * @return the value of user_opertion.opt_time
     *
     * @mbg.generated
     */
    public String getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_opertion.opt_time
     *
     * @param optTime the value for user_opertion.opt_time
     *
     * @mbg.generated
     */
    public void setOptTime(String optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uuid=").append(uuid);
        sb.append(", name=").append(name);
        sb.append(", userIp=").append(userIp);
        sb.append(", optName=").append(optName);
        sb.append(", optTime=").append(optTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}