package com.example.demo.dao;

import com.example.demo.dataobject.ScklSuccessDO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScklSuccessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckl_success
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("seckillId") Long seckillId, @Param("userPhone") Long userPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckl_success
     *
     * @mbg.generated
     */
    int insert(ScklSuccessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckl_success
     *
     * @mbg.generated
     */
    ScklSuccessDO selectByPrimaryKey(@Param("seckillId") Long seckillId, @Param("userPhone") Long userPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckl_success
     *
     * @mbg.generated
     */
    List<ScklSuccessDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckl_success
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScklSuccessDO record);
}