package com.example.demo.dao;

import com.example.demo.dataobject.UserPwdDO;
import java.util.List;

import org.springframework.stereotype.Component;

@Component
public interface UserPwdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated
     */
    int insert(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated
     */
    UserPwdDO selectByPrimaryKey(Integer id);

    
    UserPwdDO selectByUserId(Integer userId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated
     */
    List<UserPwdDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pwd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPwdDO record);
}