package com.zero.dao;

import com.zero.entity.UserOpertion;
import java.util.List;

public interface UserOpertionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    int insert(UserOpertion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    UserOpertion selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    List<UserOpertion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_opertion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserOpertion record);
}